import json
import os
import re
import requests
from contextlib import asynccontextmanager

import anthropic
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

import agent
from dal import ItemCreate, ItemDAL, ItemRead, get_client, get_collection

# This section of code was generated by Claude Sonnet 4.6
# -------------------------------------------------------
MODEL_SERVICE_URL = os.environ.get("MODEL_SERVICE_URL", "http://localhost:8001")


@asynccontextmanager
async def lifespan(app: FastAPI):
    mongo_url = os.environ.get("MONGO_URL", "mongodb://localhost:27017")
    client = get_client(mongo_url)
    app.state.dal = ItemDAL(get_collection(client))
    yield
    client.close()


app = FastAPI(lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)
# -------------------------------------------------------

@app.get("/items", response_model=list[ItemRead], status_code=200)
async def get_all_items(q: str | None = None):
    items = await app.state.dal.get_all()
    if q:
        ql = q.lower()
        items = [
            it for it in items
            if ql in it.name.lower() or (it.description and ql in it.description.lower())
        ]
    return items


@app.get("/items/{item_id}", response_model=ItemRead, status_code=200)
async def get_item(item_id: str):
    item = await app.state.dal.get_one(item_id)
    if item is None:
        raise HTTPException(status_code=404, detail="Item Not Found")
    return item


@app.post("/items", response_model=ItemRead, status_code=201)
async def create_item(item: ItemCreate):
    return await app.state.dal.create(item)


@app.put("/items/{item_id}", response_model=ItemRead, status_code=200)
async def update_item(item_id: str, item: ItemCreate):
    updated = await app.state.dal.update(item_id, item)
    if updated is None:
        raise HTTPException(status_code=404, detail="Item not found")
    return updated


@app.delete("/items/{item_id}", status_code=200)
async def delete_item(item_id: str):
    deleted = await app.state.dal.delete(item_id)
    if not deleted:
        raise HTTPException(status_code=404, detail="Item not found")
    return {"message": "Item deleted", "id": item_id}


class PredictionRequest(BaseModel):
    features: list[float]

@app.post("/predict")
def predict(req: PredictionRequest):
    try:
        response = requests.post(
            f"{MODEL_SERVICE_URL}/predict",
            json={"features": req.features},
            timeout=10,
        )
        response.raise_for_status()
        return response.json()
    except requests.exceptions.ConnectionError:
        raise HTTPException(status_code=503, detail="Model service unavailable")
    except requests.exceptions.HTTPError as e:
        raise HTTPException(status_code=e.response.status_code, detail=e.response.text)

# This section of code was generated by Claude Sonnet 4.6
_llm = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY from environment

_CHAT_SYSTEM = (
    "You are a helpful assistant for the Item Manager app. "
    "Help users organize, name, and describe their inventory items. "
    "Suggest clear item names, concise descriptions, and practical categorization tips. "
    "Be brief and actionable."
)

_ANALYZE_SYSTEM = (
    "You are an item classification assistant. Analyze the provided item name and description, "
    "then respond with ONLY valid JSON in this exact format:\n"
    '{\n'
    '  "categories": ["category1", "category2"],\n'
    '  "tags": ["tag1", "tag2", "tag3"],\n'
    '  "sentiment": "positive" | "negative" | "neutral",\n'
    '  "summary": "one sentence summary of the item"\n'
    '}\n'
    "Do not include any text outside the JSON object."
)

_ANALYZE_FEW_SHOT = (
    'Example:\n'
    'Input: "Blue Mechanical Keyboard - Compact TKL with Cherry MX Blue switches, RGB backlight, USB-C. Great for gaming."\n'
    'Output: {"categories": ["electronics", "peripherals"], "tags": ["keyboard", "mechanical", "RGB", "gaming", "USB-C"], '
    '"sentiment": "positive", "summary": "Compact RGB mechanical gaming keyboard with Cherry MX Blue switches."}'
)


class ChatRequest(BaseModel):
    message: str
    conversation_history: list = []


class ChatResponse(BaseModel):
    reply: str
    conversation_history: list


@app.post("/chat", response_model=ChatResponse)
def chat(request: ChatRequest):
    messages = request.conversation_history + [{"role": "user", "content": request.message}]
    try:
        response = _llm.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=512,
            system=_CHAT_SYSTEM,
            messages=messages,
        )
        reply = response.content[0].text
        updated_history = messages + [{"role": "assistant", "content": reply}]
        return ChatResponse(reply=reply, conversation_history=updated_history)
    except anthropic.APIStatusError as e:
        raise HTTPException(status_code=e.status_code, detail=e.message)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


class AnalyzeRequest(BaseModel):
    content: str


@app.post("/analyze")
def analyze(request: AnalyzeRequest):
    prompt = _ANALYZE_FEW_SHOT + "\n\nNow analyze this:\n" + request.content
    try:
        response = _llm.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=512,
            system=_ANALYZE_SYSTEM,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.2,
        )
        raw = response.content[0].text.strip()
        if raw.startswith("```"):
            raw = raw.split("```", 2)[1]
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()
        result = json.loads(raw)
        for field in ("categories", "tags", "sentiment", "summary"):
            if field not in result:
                raise ValueError(f"Missing field: {field}")
        return result
    except json.JSONDecodeError:
        raise HTTPException(status_code=422, detail="LLM returned invalid JSON. Try again.")
    except ValueError as e:
        raise HTTPException(status_code=422, detail=str(e))
    except anthropic.APIStatusError as e:
        raise HTTPException(status_code=e.status_code, detail=e.message)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
# --------------------------------------------------------------


# ── RAG: POST /ask ────────────────────────────────────────────────────────────
# A lightweight retrieval-augmented-generation endpoint over the item collection.
# Retrieve (keyword overlap against Mongo) -> Augment (stuff items into the prompt)
# -> Generate (Claude answers using ONLY that context). No external vector store.
_ASK_SYSTEM = (
    "You are a retrieval-augmented assistant for the Item Manager app. "
    "Answer the user's question using ONLY the item context provided. "
    "Be concise. If the context does not contain the answer, say you don't have "
    "that information in the collection — do not invent items."
)


def _retrieve(question: str, items: list[ItemRead], k: int = 5) -> list[ItemRead]:
    """Rank items by keyword overlap with the question (simple lexical retrieval)."""
    terms = set(re.findall(r"[a-z0-9]+", question.lower()))
    scored = []
    for it in items:
        text = f"{it.name} {it.description or ''}".lower()
        words = set(re.findall(r"[a-z0-9]+", text))
        score = len(terms & words)
        if score:
            scored.append((score, it))
    if not scored:
        # Nothing matched lexically — fall back to a small slice so the model
        # still has context to ground a "no relevant info" style answer.
        return items[:k]
    scored.sort(key=lambda pair: pair[0], reverse=True)
    return [it for _, it in scored[:k]]


class AskRequest(BaseModel):
    question: str


class AskResponse(BaseModel):
    answer: str
    sources: list[ItemRead]


@app.post("/ask", response_model=AskResponse)
async def ask(req: AskRequest):
    items = await app.state.dal.get_all()
    sources = _retrieve(req.question, items)
    if not sources:
        return AskResponse(
            answer="There are no items in the collection yet, so I can't answer from it.",
            sources=[],
        )
    context = "\n".join(
        f"- {it.name}: {it.description or '(no description)'}" for it in sources
    )
    prompt = (
        f"Item context:\n{context}\n\n"
        f"Question: {req.question}\n\n"
        "Answer using only the context above."
    )
    try:
        response = _llm.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=512,
            system=_ASK_SYSTEM,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.2,
        )
        return AskResponse(answer=response.content[0].text, sources=sources)
    except anthropic.APIStatusError as e:
        raise HTTPException(status_code=e.status_code, detail=e.message)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# ── Agent: POST /agent and POST /agent/confirm ────────────────────────────────
# Defined as sync `def` endpoints so FastAPI runs them in a threadpool. The agent
# makes blocking HTTP calls back to this same app (/items, /ask) with `requests`;
# running off the main event loop lets those self-calls be served concurrently.
class AgentRequest(BaseModel):
    task: str
    max_steps: int | None = None


class ConfirmRequest(BaseModel):
    session_id: str
    approved: bool


@app.post("/agent")
def run_agent(req: AgentRequest):
    """Accept a task, run the agent loop, return the result + reasoning trace."""
    try:
        return agent.run_agent_task(req.task, req.max_steps)
    except anthropic.APIStatusError as e:
        raise HTTPException(status_code=e.status_code, detail=e.message)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/agent/confirm")
def confirm_agent(req: ConfirmRequest):
    """Approve or deny a paused destructive action and resume the agent."""
    try:
        return agent.confirm_action(req.session_id, req.approved)
    except KeyError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except ValueError as e:
        raise HTTPException(status_code=409, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


app.mount("/", StaticFiles(directory="static", html=True), name="static")
