import os
import torch
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from dal import ItemCreate, ItemDAL, ItemRead, get_client, get_collection
from model import MoonClassifier


# This portion of code was generated by Claude Code to help me connect using docker env variables.
@asynccontextmanager
async def lifespan(app: FastAPI):
    mongo_url = os.environ.get("MONGO_URL", "mongodb://localhost:27017")
    client = get_client(mongo_url)
    app.state.dal = ItemDAL(get_collection(client))

    moon_model = MoonClassifier()
    moon_model.load_state_dict(torch.load("model.pth", map_location="cpu"))
    moon_model.eval()
    app.state.model = moon_model

    yield
    client.close()


app = FastAPI(lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/items", response_model=list[ItemRead], status_code=200)
async def get_all_items():
    return await app.state.dal.get_all()


@app.get("/items/{item_id}", response_model=ItemRead, status_code=200)
async def get_item(item_id: str):
    item = await app.state.dal.get_one(item_id)
    if item is None:
        raise HTTPException(status_code=404, detail="Item Not Found")
    return item


@app.post("/items", response_model=ItemRead, status_code=201)
async def create_item(item: ItemCreate):
    return await app.state.dal.create(item)


@app.put("/items/{item_id}", response_model=ItemRead, status_code=200)
async def update_item(item_id: str, item: ItemCreate):
    updated = await app.state.dal.update(item_id, item)
    if updated is None:
        raise HTTPException(status_code=404, detail="Item not found")
    return updated


@app.delete("/items/{item_id}", status_code=200)
async def delete_item(item_id: str):
    deleted = await app.state.dal.delete(item_id)
    if not deleted:
        raise HTTPException(status_code=404, detail="Item not found")
    return {"message": "Item deleted", "id": item_id}


class PredictionRequest(BaseModel):
    features: list[float]


@app.post("/predict")
def predict(req: PredictionRequest):
    if len(req.features) != 2:
        raise HTTPException(status_code=422, detail="Expected exactly 2 features [x1, x2]")

    tensor = torch.tensor([req.features], dtype=torch.float32)

    with torch.no_grad():
        logits = app.state.model(tensor)
        probs = torch.softmax(logits, dim=1)
        pred_class = probs.argmax(dim=1).item()
        confidence = probs[0][pred_class].item()

    return {
        "prediction": f"class_{pred_class}",
        "confidence": round(confidence, 4),
    }


# Static files must be mounted AFTER all API routes
app.mount("/", StaticFiles(directory="static", html=True), name="static")